prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 6h
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi

grafana:
  enabled: true
  adminPassword: admin

alertmanager:
  enabled: false

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 32Mi